language: scala
jdk:
- oraclejdk8
scala:
- 2.12.6
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
stages:
- name: test
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never