language: scala
jdk:
- openjdk8
scala:
- 2.12.10
cache:
  directories:
  - "$HOME/.sbt/1.0"
  - "$HOME/.sbt/boot"
  - "HOME/.sbt/cache"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"
stages:
- name: test
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
